apiVersion: v1
kind: Service
metadata:
  name: k8s-health-checker
  namespace: k8s-health-checker
  labels:
    app: k8s-health-checker
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: k8s-health-checker
